django/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
    path('addpost/', views.addpostmove, name='addpostmove'),
    path('post_new/', views.post_new_modelform, name='post_new_modelform'),
    path('post_edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post_edit_form/<int:pk>', views.post_edit_form, name='post_edit_form'),
    path('post_remove/<int:pk>', views.post_remove, name='post_remove'),

]

django/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('change/', views.change, name='change'),
]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    #path('common/', include('common.urls')),
    path('covid_checker', include('covid_checker.urls')),
    path('dust_checker', include('dust_checker.urls')),
    path('table', include('table.urls')),
    path('abroad_checker', include('abroad_checker.urls')),
    path('covid/', include('covid.urls')),
    path('i18n/',include('django.conf.urls.i18n')),
]

django/common/models.py
from django.db import models


from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    is_admin = models.BooleanField(default=False)

# Create your models here.

django/common/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "password")

django/common/views.py
from django.contrib.auth import login as auth_login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Profile 
from django.contrib.auth.models import User
from django.core.cache import cache 
from django.contrib.auth.forms import AuthenticationForm


def index(request):
#    cache.set("testkey", "test_value", timeout=60 * 60)
    return render(request, 'main.html')


def register(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"],
                email=request.POST["email"])
            profile = Profile(
                user=user,
                name=request.POST["name"],
                is_admin=request.POST.get('is_admin', '') == 'on')
            profile.save()
            return redirect('/')
    else:
        return render(request, 'common/register.html')

def login(request):

    if request.method == 'POST':
    	# 첫번째 인자로 request 를 받아야 한다.
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # 유효성 검사를 통과하면 세션을 create 해야 함 -> login()
            auth_login(request, form.get_user())
            # url 에 next 가 있을 때랑 없을때 결과가 다름
            return redirect(request.GET.get('next') or 'articles:index')
    else:
    	# 로그인에 필요한 빈 종이를 생성해서 lognin.html 에 전달
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'common/login.html', context)

def change(request):
    if request.method == "POST":
        profile = Profile.objects.get(user=request.user)
        profile.name = request.POST["name"]
        profile.is_admin = request.POST.get('is_admin', '') == 'on'
        profile.save()
        return redirect('/')
    else:
        return render(request, 'common/change.html')

#Create your views here.

django/templates/common/change.html
<form method="post" class="post-form" action="{% url 'common:change' %}">
  {% csrf_token %}
  <!-- Heading -->
  <h3 class="dark-grey-text text-center">
    <strong>프로필 변경</strong>
  </h3>
  <hr>
  <div class="md-form">
    <i class="fas fa-user prefix grey-text"></i>
    <input type="text" name="username" id="username" class="form-control" value="{{ request.user }}" readonly>
  </div>
  <div class="md-form">
    <i class="fas fa-envelope prefix grey-text"></i>
    <input type="email" name="email" id="email" class="form-control" value="{{ request.user.email }}" readonly>
  </div>                                        
  <div class="md-form">
    <i class="fas fa-signature prefix grey-text"></i>
    <input type="text" name="name" id="name" class="form-control" value="{{ request.user.profile.name }}">
  </div>                                   
  <div class="md-form custom-control custom-checkbox ml-4">
    <input type="checkbox" class="custom-control-input" name="is_admin" id="is_admin">
    <label class="custom-control-label" for="is_admin">관리자 여부</label>
  </div>                      
  <div class="text-center">
    <button class="btn btn-indigo">프로필 변경</button>
  </div>                   
  </form>

<script type="text/javascript">
    {% if request.user.profile.is_admin %}
        $("input:checkbox[id='is_admin']").attr("checked", true);
    {% else %}
        $("input:checkbox[id='is_admin']").attr("checked", false);
    {% endif %}
</script>

django/templates/common/login.html
{% load static %}
{% load i18n %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">

<div class="sidenav">
	<div class="login-main-text">
	   <a href="/"  style="text-decoration:none; color:#ffffff;"><h2 >{% trans "구르美" %}<br> Login Page</h2></a>
	</div>
 </div>
 <div class="main">
	<div class="col-md-6 col-sm-12">
	   <div class="login-form">
		  <form method="post" class="post-form" action="{% url 'common:login' %}">
			{% csrf_token %}
			 <div class="form-group">
				<label for="username">{% trans "아이디" %}</label>
				<input type="text" name="username" id="username" class="form-control">
			 </div>
			 <div class="form-group">
				<label for="password">{% trans "패스워드" %}</label>
				<i class="fas fa-key prefix grey-text"></i>
	  			<input type="password" name="password" id="password" class="form-control">
	  			
			 </div>
			 <div class="text-center">
			 <button type="submit" class="btn btn-black">Login</button>
			 <hr><a href="{% url 'common:register' %}">{% trans "회원이 아닌가요? 회원가입" %}</a>
			</div>
		  </form>
	   </div>
	</div>
 </div>

django/templates/common/register.html
{% load static %}
{% load i18n %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">

<div class="sidenav">
	<div class="login-main-text">
    <a href="/"  style="text-decoration:none; color:#ffffff;"><h2 >{% trans "구르美" %}<br> Signup Page</h2></a>
	</div>
 </div>
 <div class="main">
	<div class="col-md-6 col-sm-12">
	   <div class="login-form">

  <form method="post" class="post-form" action="{% url 'common:register' %}">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">{% trans "아이디" %}</label>
      <i class="fas fa-user prefix grey-text"></i>
      <input type="text" name="username" id="username" class="form-control">
    </div>
    <div class="form-group">
      <label for="password1">{% trans "패스워드" %}</label>
      <i class="fas fa-key prefix grey-text"></i>
      <input type="password" name="password1" id="password1" class="form-control">
    </div>
    <div class="form-group">
      <label for="password2">{% trans "패스워드 확인" %}</label>
      <i class="fas fa-key prefix grey-text"></i>
      <input type="password" name="password2" id="password2" class="form-control">
    </div>                    
    <div class="form-group">
      <label for="email">{% trans "이메일" %}</label>
      <i class="fas fa-envelope prefix grey-text"></i>
      <input type="email" name="email" id="email" class="form-control">
    </div>                                        
    <div class="form-group">
      <label for="name">{% trans "성명" %}</label>
      <i class="fas fa-signature prefix grey-text"></i>
      <input type="text" name="name" id="name" class="form-control">
    </div>                                   
    <div class="md-form custom-control custom-checkbox ml-4">
      <input type="checkbox" class="custom-control-input" name="is_admin" id="is_admin">
      <label class="custom-control-label" for="is_admin">{% trans "관리자 여부" %}</label>
    </div>                      
    <div class="text-center">
      <button type="submit" class="btn btn-black">{% trans "회원가입" %}</button>
      <hr><a href="{% url 'common:login' %}">{% trans "회원이신가요? 로그인" %}</a>
    </div>                    
  </form>
</div>
</div>
</div>

django/templates/common/signup.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" action="{% url 'common:signup' %}" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>