django/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
    path('addpost/', views.addpostmove, name='addpostmove'),
    path('post_new/', views.post_new_modelform, name='post_new_modelform'),
    path('post_edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post_edit_form/<int:pk>', views.post_edit_form, name='post_edit_form'),
    path('post_remove/<int:pk>', views.post_remove, name='post_remove'),

]

django/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('change/', views.change, name='change'),
]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    #path('common/', include('common.urls')),
    path('covid_checker', include('covid_checker.urls')),
    path('dust_checker', include('dust_checker.urls')),
    path('table', include('table.urls')),
    path('abroad_checker', include('abroad_checker.urls')),
    path('covid/', include('covid.urls')),
    path('i18n/',include('django.conf.urls.i18n')),
]

django/covid/urls.py
from django.urls import path
from . import views

app_name = 'covid'

urlpatterns = [
    path('', views.index, name='index'),
]

django/covid_checker/urls.py
from django.urls import path
from . import views

app_name = 'covid_checker'

urlpatterns = [
    path('', views.index, name='index')
]

django/table/urls.py
from django.urls import path
from . import views

app_name = 'table'

urlpatterns = [
    path('', views.index, name='index')
]

django/templates/header.html
{% load static %}
{% load i18n %}
    <!-- Vendor CSS Files -->
        <link href='{% static "/vendor/animate.css/animate.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/bootstrap-icons/bootstrap-icons.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/boxicons/css/boxicons.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/glightbox/css/glightbox.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/swiper/swiper-bundle.min.css" %}' rel="stylesheet">
        <link href='{% static "/css/style.css" %}' rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

        <!-- Template Main CSS File -->

<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center justify-content-between">

    <h1 class="logo"><a href="/">{% trans "구르美" %}</a></h1>
    <!-- Uncomment below if you prefer to use an image logo -->
    <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="/">Home</a></li>
        <li><a class="nav-link scrollto " href="{% url 'board:index' %}">{% trans "공유의장" %}</a></li>
        <li><a class="nav-link scrollto" href="{% url 'covid_checker:index' %}">{% trans "코로나 현황" %}</a></li>
         <li><a class="nav-link scrollto" href="{% url 'covid:index' %}">{% trans "해외 코로나 현황" %}</a></li>
        <li><a class="nav-link scrollto" href="{% url 'table:index' %}">{% trans "해외 입국 현황" %}</a></li>
        {% if user.is_authenticated %}
        <li><a class="getstarted scrollto" href="{% url 'common:logout' %}">Logout</a></li>
        {% else %}
        <li><a class="getstarted scrollto" href="{% url 'common:login' %}">Login</a></li>
        <li><a class="getstarted scrollto" href="{% url 'common:register' %}">Sign up</a></li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav><!-- .navbar -->
  </div>
</header><!-- End Header -->
<!-- Vendor JS Files -->
<script src='{% static "/vendor/purecounter/purecounter.js" %}'></script>
<script src='{% static "/vendor/bootstrap/js/bootstrap.bundle.min.js" %}'></script>
<script src='{% static "/vendor/glightbox/js/glightbox.min.js" %}'></script>
<script src='{% static "/vendor/isotope-layout/isotope.pkgd.min.js" %}'></script>
<script src='{% static "/vendor/swiper/swiper-bundle.min.js" %}'></script>
<script src='{% static "/vendor/php-email-form/validate.js" %}'></script>

<!-- Template Main JS File -->
<script src='{% static "/js/main.js" %}'></script>

django/templates/main.html
<!doctype html>
<html lang="ko">
  {% load static %}
  {% load i18n %}
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
      
        <title>cloud web project</title>
        <meta content="" name="description">
        <meta content="" name="keywords">
      
        <!-- Favicons -->
        <link href="assets/img/favicon.png" rel="icon">
        <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
      
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
      
        <!-- Vendor CSS Files -->
        <link href='{% static "/vendor/animate.css/animate.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/bootstrap/css/bootstrap.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/bootstrap-icons/bootstrap-icons.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/boxicons/css/boxicons.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/glightbox/css/glightbox.min.css" %}' rel="stylesheet">
        <link href='{% static "/vendor/swiper/swiper-bundle.min.css" %}' rel="stylesheet">
      
        <!-- Template Main CSS File -->
        <link href='{% static "/css/style.css" %}' rel="stylesheet">
      
        <!-- =======================================================
        * Template Name: Groovin - v4.7.1
        * Template URL: https://bootstrapmade.com/groovin-free-bootstrap-theme/
        * Author: BootstrapMade.com
        * License: https://bootstrapmade.com/license/
        ======================================================== -->
      </head>
<body>
  <article>
    {% include "header.html" %} 
  <section id="hero">
    <div class="hero-container">
      <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

        <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <!-- Slide 1 -->
          <div class="carousel-item active" style="background-image: url(https://cdn.pixabay.com/photo/2020/05/25/17/03/travel-5219496_960_720.jpg);">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">{% trans "Enjoy your trip" %}</h2>
                <p class="animate__animated animate__fadeInUp"></p>
                <div>
                
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 2 -->
          <div class="carousel-item" style="background-image: url(https://cdn.pixabay.com/photo/2014/04/02/14/09/world-map-306338_960_720.png);">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">{% trans "코로나 현황" %}</h2>
                  <p class="animate__animated animate__fadeInUp">{% trans "실시간  정보를 알아보세요." %}</p>
		<div>
                  <a href="{% url 'covid_checker:index' %}" class="btn-get-started animate__animated animate__fadeInUp scrollto">Go</a>
                </div>
              </div>
            </div>
          </div>

          <!-- Slide 3 -->
          <div class="carousel-item" style="background-image: url(https://cdn.pixabay.com/photo/2017/09/20/11/27/bulletin-board-2768204_960_720.jpg);">
            <div class="carousel-container">
              <div class="carousel-content">
                <h2 class="animate__animated animate__fadeInDown">{% trans "공유의 장" %}</h2>
                <p class="animate__animated animate__fadeInUp">{% trans "많은 사람과 이야기를 공유해보세요." %}</p>
                <div>
                  <a href="{% url 'board:index' %}" class="btn-get-started animate__animated animate__fadeInUp scrollto">Go</a>
                </div>
              </div>
            </div>
          </div>

        </div>

        <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
          <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
        </a>

        <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
          <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
        </a>

      </div>
    </div>
  </section><!-- End Hero -->

  
</article>

<footer id="footer">
  <div class="container">
    <div class="copyright">
      &copy; Copyright <strong><span>Groovin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/groovin-free-bootstrap-theme/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
    <div class="copyright"><form action="{% url 'set_language' %}" method="post">
      {% csrf_token %}
      <select class="from-control" name="language">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                  {{ language.name_local }} ({{ language.code }})
              </option>
          {% endfor %}
      </select>
      <input class="btn btn-outline-success" type="submit" value="Switch">
  </form></div>
  </div>
</footer><!-- End Footer -->



<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

</form>
</body>
</html>