django/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
    path('addpost/', views.addpostmove, name='addpostmove'),
    path('post_new/', views.post_new_modelform, name='post_new_modelform'),
    path('post_edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post_edit_form/<int:pk>', views.post_edit_form, name='post_edit_form'),
    path('post_remove/<int:pk>', views.post_remove, name='post_remove'),

]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    #path('common/', include('common.urls')),
    path('covid_checker', include('covid_checker.urls')),
    path('dust_checker', include('dust_checker.urls')),
    path('table', include('table.urls')),
    path('abroad_checker', include('abroad_checker.urls')),
    path('covid/', include('covid.urls')),
    path('i18n/',include('django.conf.urls.i18n')),
]

django/dust_checker/urls.py
from django.urls import path
from . import views

app_name = 'dust_checker'

urlpatterns = [
    path('', views.index, name='index'),
    path('/detail', views.detail, name='detail'),
]

django/dust_checker/models.py
from django.db import models

# Create your models here.

django/dust_checker/views.py
from django.shortcuts import render
from .api import check_air

def index(request):
    res = check_air()
    pm10 = res.get('중구')
    context = {'station': '중구', 'pm10': pm10}
    return render(request, 'dust_checker/dust_main.html', context)

def detail(request):
    res = check_air()
    context = {'dust': res}
    return render(request, 'dust_checker/dust_detail.html', context)

django/templates/dust_checker/dust_detail.html
{% extends 'main.html' %}
{% block content %}
<!-- ---------------------- [edit] ------------------------ -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<div class="row justify-content-center mb-2">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    {% for key in dust.keys %}
                        <th scope="col">{{key}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for value in dust.values %}
                        <td>{{value}}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="d-flex justify-content-center mb-2">
    <div class="col-md-6">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script>
var label = new Array();
var data = new Array();
{% for key, value in dust.items %}
    label.push('{{key}}');
    data.push('{{value}}');
{% endfor %}


var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: label,
        datasets: [{
            label: '미세먼지 수치',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: data
        }]
    },

    // Configuration options go here
    options: {}
});
</script>
<!-- -------------------------------------------------------- -->
{% endblock %}

django/templates/dust_checker/dust_main.html
{% include "header.html" %} 
{% block content %}
{% load static %}
<link href='{% static "/css/style.css" %}' rel="stylesheet">
<section id="about" class="about" >
    <div class="container">
        
</div>
<section id="about" class="about" >
    <div class="container">
        
</div>
<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <div class="card" >
            <img src="/static/images/dust.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">미세먼지 수치</h5>
		<p class="card-text">{{pm10}}</p>
            	<a href="{% url 'dust_checker:detail'%}" class="btn btn-primary">>> 자세히</a>
	    </div>
        </div>
    </div>
</div>
{% endblock %}