django/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:postId>/', views.detail, name='detail'),
    path('answer/create/<int:postId>/', views.answer_create, name='answer_create'),
    path('addpost/', views.addpostmove, name='addpostmove'),
    path('post_new/', views.post_new_modelform, name='post_new_modelform'),
    path('post_edit/<int:pk>', views.post_edit, name='post_edit'),
    path('post_edit_form/<int:pk>', views.post_edit_form, name='post_edit_form'),
    path('post_remove/<int:pk>', views.post_remove, name='post_remove'),

]

django/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    #path('common/', include('common.urls')),
    path('covid_checker', include('covid_checker.urls')),
    path('dust_checker', include('dust_checker.urls')),
    path('table', include('table.urls')),
    path('abroad_checker', include('abroad_checker.urls')),
    path('covid/', include('covid.urls')),
    path('i18n/',include('django.conf.urls.i18n')),
]

django/board/models.py
from django.db import models
from django.utils import timezone
from django import forms

# title 필드의 length가 2보다 작으면 검증오류 발생시키는 함수 선언하기
def min_length_2_validator(value):
    if len(value) < 2:
        # ValidataionError 예외를 강제로 발생시킨다
        raise forms.ValidationError('title은 2글자 이상 입력해 주세요!')

class Post(models.Model):
    title = models.CharField(max_length=200, validators=[min_length_2_validator])
    content = models.TextField()
    writer = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title +'(' + str(self.id) + ')'


class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.CharField(max_length=20)
    date = models.DateTimeField()

    def __str__(self):
        return self.title
# Create your models here.

django/board/forms.py
from django import forms
from .models import Post


# ModelForm을 상속받는 PostModelForm 클래스 정의
class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', )


def min_length_5_validator(value):
    if len(value) < 5:
        # ValidataionError 예외를 강제로 발생시킨다
        raise forms.ValidationError('text은 5글자 이상 입력해 주세요!')

# Form을 상속받는 PostForm 클래스 정의
class PostForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea, validators=[min_length_5_validator])

django/board/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from .models import Post
from django.contrib.auth.decorators import login_required
from .forms import PostModelForm, PostForm

def index(request):
    # 게시물 목록 출력
    postList = Post.objects.order_by('-date')
    context = {'postList': postList}
    return render(request, 'board/list.html', context)

def detail(request, postId):
    # 상세보기
    post = Post.objects.get(id=postId)
    context = {'post': post}
    return render(request, 'board/detail.html', context)

def answer_create(request, postId):
    # 답글 추가
    post = get_object_or_404(Post, pk=postId)
    post.answer_set.create(content=request.POST.get('content'), date=timezone.now())
    return redirect('board:detail', postId=postId)
#Create your views here.

def addpostmove(request):

    return render(request, 'board/addpost.html')

    
# 글등록(Form) 사용
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            # 검증을 통과한 입력 데이터
            print(form.cleaned_data)
            clean_data_dict = form.cleaned_data
            # create() 함수가 호출되면 등록처리가 이루어진다.
            post = Post.objects.create(
                writer=request.user,
                title = clean_data_dict['title'],
                content=clean_data_dict['content'],
                date=timezone.now()
            )
            postList = Post.objects.order_by('-date')
            context = {'postList': postList}
            return redirect('/', context)


@login_required
def post_new_modelform(request):
    if request.method == 'POST':
        # 등록을 요청하는 경우
        post_form = PostModelForm(request.POST)
        # 검증로직을 통과하면
        if post_form.is_valid():
            # form 객체의 save() 호출하면 Model 객체가 생성되어진다.
            post = post_form.save(commit=False)
            # 로그인된 username을 작성자(author)필드에 저장
            post.writer = request.user
            # 현재날짜시간을 게시일자(published_date) 필드에 저장
            post.date = timezone.now()
            # post 객체가 저장되면서 insert 처리가 되어진다.
            post.save()
            # 등록 후에 상세페이지로 리다이렉션 처리하기

            postList = Post.objects.order_by('-date')
            context = {'postList': postList}
            return redirect('/board', context)

# 글수정(ModelForm) 사용
@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            # form 객체의 save() 호출하면 Model 객체가 생성되어진다.
            post = form.save(commit=False)
            # 로그인된 username을 작성자(author)필드에 저장
            post.writer = request.user
            # 현재날짜시간을 게시일자(published_date) 필드에 저장
            post.date = timezone.now()
            # post 객체가 저장되면서 insert 처리가 되어진다.
            post.save()
            # 등록 후에 상세페이지로 리다이렉션 처리하기
            post = Post.objects.get(id=pk)
            context = {'post': post}
            return redirect('board:detail', pk)

# 글수정(ModelForm) 사용
@login_required
def post_edit_form(request, pk):
    b=Post.objects.get(id=pk)
    data = {"post":b}
    return render(request, 'board/editpost.html',data)

# 글삭제
@login_required
def post_remove(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('/board')

django/templates/board/addpost.html
{% include "header.html" %} 
{% block content %}
{% load static %}
<link href='{% static "/css/style.css" %}' rel="stylesheet">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
<div class="container">

    <form action="{% url 'board:post_new_modelform'%}" method="post">
        <div class="form-group">
            {% csrf_token%}
            <p><label>제목</label><input name="title" class="form-control"></p>
            <p><label>내용</label></p>
            <textarea name="content" cols="50" rows="20" class="form-control"></textarea>

        </div>
        <div class="form-group"style="float: right; margin-top: 20px;">
        <p><input type="submit" class="btn btn-outline-success pull-right" value="게시물 저장"></p>
        </div>
        </form>
    </div>
    
    {% endblock %}

django/templates/board/detail.html
{% include "header.html" %} 
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link href='{% static "/css/style.css" %}' rel="stylesheet">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
            
            <div class="card shadow mb-4">
                <div class="card-header py-3">
<div class="container">
<div class="container my-3">
    <div style="float: right;">
    <a href="/board"><button class="btn btn-outline-success">목록으로 돌아가기</button></a>
</div>
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ post.date }}</div>
            </div>
        </div>
    </div>
    <div>
        {% if post.writer == user %}
        <a href="{% url 'board:post_edit_form' post.id %}"><button class="btn btn-outline-success">글 수정</button></a>
       <button class="btn btn-outline-danger" id = "del_qna" type = "button" onclick="fn_del_qna();">글 삭제</button>
        {% endif %}
    </div>
    <h5 class="border-bottom my-3 py-2">{{post.answer_set.count}}개의 답글이 있습니다.</h5>
    {% for answer in post.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{ answer.date }}</div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답글등록" class="btn btn-outline-success">
    </form>
</div>

<script>
    function fn_del_qna(){
          var res = confirm('게시글을 정말로 삭제하시겠습니까?');
          if(res){
            window.location.href = "{% url 'board:post_remove' post.id %}"
            alert("성공적으로 삭제되었습니다.");
          }
        }
    </script>
{% endblock %}

django/templates/board/editpost.html
{% include "header.html" %} 
{% block content %}
{% load static %}
<link href='{% static "/css/style.css" %}' rel="stylesheet">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
            <div class="container">

                <form action="{% url 'board:post_edit' post.id%}" method="post">
                    <div class="form-group">
                        {% csrf_token%}
                        <p><label>제목</label><input name="title" value="{{ post.title }}" class="form-control"></p>
                        <p><label>내용</label></p>
                        <textarea name="content" cols="50" rows="20" class="form-control">{{ post.content }}</textarea>
            
                    </div>
                    <div class="form-group"style="float: right; margin-top: 20px;">
                    <p><input type="submit" class="btn btn-outline-success pull-right" value="수정하기"></p>
                    </div>
                    </form>
                </div>
{% endblock %}

django/templates/board/list.html
{% include "header.html" %} 
{% block content %}
{% load static %}
<link href='{% static "/css/style.css" %}' rel="stylesheet">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
        
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th><th>제목</th><th>작성일시</th><th>작성자</th>
            </tr>
        </thead>
        <tbody>
        {% if postList %}
        {% for post in postList %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'board:detail' post.id %}">{{ post.title }}</a></td>
            <td>{{ post.date }}</td>
            <td>{{ post.writer }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr><td colspan="3">게시물이 없습니다.</td></tr>
        {% endif %}
        </tbody>
    </table>

    <div style="float: right; margin-top: 20px;">
    {% if user.is_authenticated %}
    <a href="{% url 'board:addpostmove' %}"><button class="btn btn-outline-success">글쓰기</button></a>
    {% endif %}
    </div>
</div>
</div>
</div>
</div>
</section>
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>